services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    # DBMS 
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  pgdata: